# Generated by Django 6.0.1 on 2026-01-13 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включить напоминания')),
                ('reminder_time', models.TimeField(default='09:00', verbose_name='Время напоминания')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('telegram_notifications', models.BooleanField(default=False, verbose_name='Telegram уведомления')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, verbose_name='Telegram Chat ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
