# Generated by Django 6.0.1 on 2026-01-13 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remindersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название достижения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('streak_length', models.PositiveIntegerField(verbose_name='Длина серии')),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Изображение')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичное')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achieved_at'],
            },
        ),
    ]
